# Generated by Django 5.1.3 on 2024-11-13 08:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cupom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('data_validade', models.DateField(verbose_name='Validade')),
                ('data_ativacao', models.DateField(default=django.utils.timezone.now, verbose_name='Ativação')),
                ('valor_desconto_percentual', models.FloatField(verbose_name='Desconto persentual')),
            ],
        ),
        migrations.CreateModel(
            name='FormaPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=255)),
                ('descricao', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TipoEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, verbose_name='Slug')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='TipoStatusEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255)),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='TipoStatusPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=255)),
                ('descricao', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_final', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total final')),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor pago')),
                ('valor_restante', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor restante')),
                ('cliente_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='servico.cliente')),
                ('cupom_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='servico.cupom')),
                ('forma_pagamento_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='servico.formapagamento')),
                ('tipo_status_pedido_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='servico.tipostatuspedido')),
            ],
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_prevista', models.DateField(verbose_name='Data prevista')),
                ('data_entregue', models.DateField(verbose_name='Data entregue')),
                ('taxa', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Taxa')),
                ('pedido_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='servico.pedido')),
                ('tipo_entrega', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='servico.tipoentrega')),
                ('tipo_status_entrega_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='servico.tipostatusentrega')),
            ],
        ),
    ]
